### PR TITLE
TRRS: add missing stabilizer hole for reverse footprint

### PR DESCRIPTION
**Pull request by Miigon**

### CODE REVIEW

**Comment by Miigon** [comment]
This is how it currently looks like:
#### normal
截屏2022-05-03 下午3 09 52
#### reverse
截屏2022-05-03 下午3 09 34
#### reverse & symmetric
截屏2022-05-03 下午3 10 10

**Comment by Miigon** [comment]
This PR solves the same problem as #44 (but properly)

**Comment by mrzealot** [comment]
Excellent work, thanks! Sorry it took me so long to get to it, but it's finally merged into `develop`! :+1:

**Comment by mrzealot** [comment]
Oh, and also: closes #44

**Pull request closed without merging**
